# Generated by Django 5.2.15 on 2026-06-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='taille',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('haut', 'Vêtement Haut'), ('bas', 'Vêtement Bas'), ('chaussure', 'Chaussure')], default='haut', max_length=20),
        ),
    ]
