# Generated by Django 5.2.15 on 2026-06-14 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_article_taille_alter_article_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46')], max_length=4)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='Articles.article')),
            ],
            options={
                'verbose_name': 'Variation de taille',
                'verbose_name_plural': 'Variations de taille',
                'unique_together': {('article', 'taille')},
            },
        ),
    ]
