# Generated by Django 5.2.15 on 2026-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlevariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='article',
            name='couleur',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='articlevariant',
            name='couleur',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='articlevariant',
            unique_together={('article', 'taille', 'couleur')},
        ),
    ]
