# Generated by Django 5.2.15 on 2026-09-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_alter_articlevariant_unique_together_article_couleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('haut', 'Vêtement Haut'), ('bas', 'Vêtement Bas'), ('chaussure', 'Chaussure'), ('autre', 'Autre')], default='haut', max_length=20),
        ),
    ]
