# Generated by Django 5.2.15 on 2026-06-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0003_utilisateur_code_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_validation',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
