# Generated by Django 5.2.15 on 2026-06-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0005_remove_utilisateur_code_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
