# Generated by Django 5.2.15 on 2026-07-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0006_commande_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
