# Generated by Django 5.2.15 on 2026-07-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0011_utilisateur_code_validation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='code_validation',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='code_validation_expires',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='email_verified',
        ),
    ]
