# Generated by Django 5.2.15 on 2026-07-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0012_remove_utilisateur_code_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='ticket',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
