# Generated by Django 5.2.15 on 2026-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0013_add_ticket_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_validation',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_validation_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
