# Generated by Django 5.2.15 on 2026-07-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0014_utilisateur_code_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='google_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
