# Generated by Django 5.2.15 on 2026-07-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0015_utilisateur_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='google_id',
        ),
    ]
