# Generated by Django 5.2.15 on 2026-07-24 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0016_remove_utilisateur_google_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('livraison_echouee', 'Livraison échouée')], db_index=True, default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='code_validation',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['user', 'statut'], name='Utilisateur_user_id_eb26fa_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['livreur', 'statut'], name='Utilisateur_livreur_0df312_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['livreur', 'lue'], name='Utilisateur_livreur_a98c92_idx'),
        ),
    ]
