# Generated by Django 5.2.15 on 2026-09-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0017_alter_commande_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='code_validation',
            field=models.CharField(blank=True, default='', help_text='Hash SHA-256 (HMAC) du code de validation.', max_length=64),
        ),
    ]
