# Generated by Django 5.2.15 on 2026-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0018_alter_utilisateur_code_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='est_disponible',
            field=models.BooleanField(default=True),
        ),
    ]
